apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: healthcare
  labels:
    app: mongodb
    app.kubernetes.io/part-of: healthcare-system
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo
