apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: healthcare
  labels:
    app: mongodb
    app.kubernetes.io/part-of: healthcare-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
